# Autogenerated by devscripts/update-version.py

__version__ = '2026.03.24.005349'

RELEASE_GIT_HEAD = 'f01e1a1ced581c13f28c7da45eb6396cb9fff6e4'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Jsoeph192/yt-dlp'

ORIGIN = 'Jsoeph192/yt-dlp'

_pkg_version = '2026.03.24.005349'
