# Autogenerated by devscripts/update-version.py

__version__ = '2026.03.21.144019'

RELEASE_GIT_HEAD = '7fd74d10097833ebce0cb162e0ccf7825de9b768'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Jsoeph192/yt-dlp'

ORIGIN = 'Jsoeph192/yt-dlp'

_pkg_version = '2026.03.21.144019'
