# Autogenerated by devscripts/update-version.py

__version__ = '2026.03.22.195526'

RELEASE_GIT_HEAD = 'bc3bbdd0129552e2fee239b5568fd370eadfd011'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Jsoeph192/yt-dlp'

ORIGIN = 'Jsoeph192/yt-dlp'

_pkg_version = '2026.03.22.195526'
